/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorymain;

import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jxseff
 */
public class Brand1 extends javax.swing.JFrame {

    /**
     * Creates new form Brand1
     */
    public Brand1() {
        initComponents();
        Connect();
        SelectProd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    PreparedStatement Pst = null;
    
     public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/brandtable", "root", "root");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        } 
}
     
     public void SelectProd() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/brandtable", "root", "root");
            St = Con.createStatement();
            Rs = (ResultSet) St.executeQuery("select * from BrandTable");
            BrandTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        InventorySystemBrand = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        ManageBrand = new javax.swing.JLabel();
        BackProduct = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BrandTable = new javax.swing.JTable();
        BrandList = new javax.swing.JLabel();
        BrandID = new javax.swing.JTextField();
        BrandName = new javax.swing.JTextField();
        BrandNameName = new javax.swing.JLabel();
        BrandIDName = new javax.swing.JLabel();
        Add_Brand = new javax.swing.JButton();
        Update_Brand = new javax.swing.JButton();
        Logout_Brand = new javax.swing.JButton();
        Delete_Brand = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(205, 180, 219));

        InventorySystemBrand.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        InventorySystemBrand.setText("GPU Inventory System");

        Close.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 36)); // NOI18N
        Close.setText("X");
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        ManageBrand.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        ManageBrand.setText("Manage Brand");

        BackProduct.setIcon(new javax.swing.ImageIcon("C:\\Users\\jxseff\\Downloads\\313090917_551572566783212_4437309445521463107_n.png")); // NOI18N
        BackProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(BackProduct)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(ManageBrand))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(InventorySystemBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Close))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackProduct)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(InventorySystemBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ManageBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 200, 221));

        BrandTable.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BrandTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Brand ID", "Brand Name"
            }
        ));
        BrandTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BrandTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BrandTable);

        BrandList.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BrandList.setText("Brand List");

        BrandID.setToolTipText("");
        BrandID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrandIDActionPerformed(evt);
            }
        });

        BrandName.setToolTipText("");
        BrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrandNameActionPerformed(evt);
            }
        });

        BrandNameName.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BrandNameName.setText("Brand Name");

        BrandIDName.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        BrandIDName.setText("Brand ID");

        Add_Brand.setBackground(new java.awt.Color(255, 175, 204));
        Add_Brand.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Add_Brand.setText("Add");
        Add_Brand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_BrandMouseClicked(evt);
            }
        });
        Add_Brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_BrandActionPerformed(evt);
            }
        });

        Update_Brand.setBackground(new java.awt.Color(255, 175, 204));
        Update_Brand.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Update_Brand.setText("Update");
        Update_Brand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_BrandMouseClicked(evt);
            }
        });
        Update_Brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_BrandActionPerformed(evt);
            }
        });

        Logout_Brand.setBackground(new java.awt.Color(255, 175, 204));
        Logout_Brand.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Logout_Brand.setText("Logout");
        Logout_Brand.setToolTipText("");
        Logout_Brand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_BrandMouseClicked(evt);
            }
        });
        Logout_Brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_BrandActionPerformed(evt);
            }
        });

        Delete_Brand.setBackground(new java.awt.Color(255, 175, 204));
        Delete_Brand.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Delete_Brand.setText("Delete");
        Delete_Brand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_BrandMouseClicked(evt);
            }
        });
        Delete_Brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_BrandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BrandNameName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BrandIDName)
                        .addGap(45, 45, 45)
                        .addComponent(BrandID, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Add_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Logout_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Update_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delete_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(711, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(653, 653, 653)
                    .addComponent(BrandList)
                    .addContainerGap(309, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(408, 408, 408)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BrandID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrandIDName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BrandNameName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logout_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BrandList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Delete_BrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_BrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_BrandActionPerformed

    private void Delete_BrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_BrandMouseClicked
        if (BrandID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter the Item to be Deleted");
        } else {
            try {
                String Id = BrandID.getText();
                String Query = "DELETE FROM brandtable WHERE BrandID="+ Id;
                Statement Remove = Con.createStatement();
                Remove.executeUpdate(Query);
                SelectProd();
                JOptionPane.showMessageDialog(this, "Brand Deleted Successfully");
            } catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Delete_BrandMouseClicked

    private void Logout_BrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_BrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_BrandActionPerformed

    private void Logout_BrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_BrandMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout_BrandMouseClicked

    private void Update_BrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_BrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_BrandActionPerformed

    private void Update_BrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_BrandMouseClicked
        if(BrandID.getText().isEmpty()||BrandName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
            try {
                String UpdateQuery = "update BrandTable set BrandName='"+BrandName.getText()+"'where BrandID='"+BrandID.getText()+"'";
                Statement Change = Con.createStatement();
                Change.executeUpdate(UpdateQuery);
                JOptionPane.showMessageDialog(this, "Brand Updated Successfully");
                SelectProd();
            }catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Update_BrandMouseClicked

    private void Add_BrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_BrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_BrandActionPerformed

    private void Add_BrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_BrandMouseClicked
        try{

            java.sql.PreparedStatement add = Con.prepareStatement("insert into BrandTable values (?, ?)");

            add.setInt(1, Integer.parseInt(BrandID.getText()));
            add.setString(2, BrandName.getText());
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Brand Successfully Added");
            Con.close();
            SelectProd();

        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Add_BrandMouseClicked

    private void BrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrandNameActionPerformed

    private void BrandIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrandIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrandIDActionPerformed

    private void BrandTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrandTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)BrandTable.getModel();
        int Myindex = BrandTable.getSelectedRow();
        BrandID.setText(model.getValueAt(Myindex, 0).toString());
        BrandName.setText(model.getValueAt(Myindex, 1).toString());
    }//GEN-LAST:event_BrandTableMouseClicked

    private void BackProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackProductMouseClicked
        new HomeForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackProductMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Brand1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Brand1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Brand1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Brand1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Brand1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Brand;
    private javax.swing.JLabel BackProduct;
    private javax.swing.JTextField BrandID;
    private javax.swing.JLabel BrandIDName;
    private javax.swing.JLabel BrandList;
    private javax.swing.JTextField BrandName;
    private javax.swing.JLabel BrandNameName;
    private javax.swing.JTable BrandTable;
    private javax.swing.JLabel Close;
    private javax.swing.JButton Delete_Brand;
    private javax.swing.JLabel InventorySystemBrand;
    private javax.swing.JButton Logout_Brand;
    private javax.swing.JLabel ManageBrand;
    private javax.swing.JButton Update_Brand;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
